version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    depends_on:
      - db
    environment:
      - DB_PASSWORD=admin

  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=admin
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: